### ISSUE TITLE
Contribute this module to Drupal.org

### ISSUE THREAD

**Issue by achourasia** [mjordan/persistent_identifiers#29]
@mjordan and others,
We have been developing patches to this module, and could contribute them here. But it would be nice to have this module on Drupal.org where others could easily discover and  benefit from this work.
Thoughts?

**Comment by mjordan** [comment]
@achourasia I'm afraid I have not had time to devote to this module, and I would not likely meet minimum requirements d.o. has for a module maintainer. I am happy to hand this module over to someone else to steward for the Islandora (and Drupal) community. I can ask on the islandora slack if anyone would like to take it over. If you're interested, let me know.

**Comment by achourasia** [comment]
@mjordan anyone can contribute modules to Drupal, there is no specific requirement. d.o has additional guidelines for module developers for opting into security advisory for modules. Other folks can assist here, but this is an optional second step. Perhaps this part gave you an impression that these are requirements, they are not.

It would be nice if you or others at islandora will be willing consider this, and I can propose someone from my team to consider as co-maintainer.

**Comment by achourasia** [comment]
The module has been cloned on Drupal.org https://www.drupal.org/project/persistent_identifiers
